function checkIfUrlHasHash(){getParameterByName("k")!=null&&getParameterByName("k")!="0"||getParameterByHash("k")!=null&&getParameterByHash("k")!="0"?($(".search-landing").show(),$(".search-root").addClass("search-result container")):($(".search-root").removeClass("search-result container"),$(".search-landing").hide())}$(window).on("hashchange",function(){checkIfUrlHasHash();getParameterByHash("s")||(setTimeout(checkAltyapi,500),setTimeout(checkEngelsiz,500),setTimeout(checksifredegistirme,500),setTimeout(checkinternetpaketleri,500),setTimeout(checktelefon,500),setTimeout(checkborcsorgulama,500),setTimeout(checkarizasorgulama,500),setTimeout(checknakilbasvuru,500),setTimeout(checkfaturaodeme,500))});checkIfUrlHasHash();
function convertTurkishChars(n){const t={"ğ":"g","ü":"u","ş":"s","ı":"i","ö":"o","ç":"c","İ":"i"};return decodeURIComponent(n).toLowerCase().replace(/[ğüşııöç]/g,n=>t[n]).replace(/\s/g,"")}function checkAltyapi(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://kapsamaharitasi.turktelekom.com.tr/",imgSrc:"/SiteAssets/images/arama-gorselleri/iste-internet.png",imgAlt:"Kapsama Haritası",title:"Kapsama Haritası",linkText:"https://kapsamaharitasi.turktelekom.com.tr/",comment:"Türk Telekom kapsama haritası"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Yardım",title:"Yardım",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet",comment:"Yardım"},{href:"https://www.turktelekom.com.tr/hakkimizda/planli-calisma-duyurulari",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Planlı Çalışma Duyuruları",title:"Planlı Çalışma Duyuruları",linkText:"https://www.turktelekom.com.tr/hakkimizda/planli-calisma-duyurulari",comment:"Planlı Çalışma Duyuruları"},{href:"https://www.turktelekom.com.tr/hakkimizda/duyurular/fiber-internet",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Fiber İnternet",title:"Fiber İnternet",linkText:"https://www.turktelekom.com.tr/hakkimizda/duyurular/fiber-internet",comment:"Fiber İnternet"},{href:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari/yeni-magnet-limitsiz-tarifesi",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Yeni Magnet Limitsiz Tarifesi",title:"Yeni Magnet Limitsiz Tarifesi",linkText:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari/yeni-magnet-limitsiz-tarifesi",comment:"Evde İnternet"},],n=="altyapi"||t=="altyapi")for(i=0;i<cardInfo.length;i++){let n=`
            <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
            <div class="image-block">
            <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
            <div class="text-block">
            <h4>${cardInfo[i].title}</h4>
            <p class="link">${cardInfo[i].linkText}</p>
            <p>${cardInfo[i].comment}</p>      
            </div>
            </a>
            `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkAltyapiInterval)}}function checktelefon(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon",imgSrc:"https://www.turktelekom.com.tr/SiteAssets/images/arama-gorselleri/mobil.png",imgAlt:"Akıllı Telefon",title:"Akıllı Telefon",linkText:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon",comment:"Akıllı Telefon"},{href:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon/iphone-14-128-gb",imgSrc:"https://bireysel.turktelekom.com.tr/tt-cihazlar/PublishingImages/akilli-telefon/apple/iPhone_14_Plus_Yellow.jpg",imgAlt:"iPhone 14 128 GB",title:"iPhone 14 128 GB",linkText:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon/iphone-14-128-gb",comment:"iPhone 14 128GB İçi dışı sıra dışı."},{href:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon/iphone-11-64gb",imgSrc:"https://bireysel.turktelekom.com.tr/tt-cihazlar/PublishingImages/akilli-telefon/apple/iPhone11-purple.jpg",imgAlt:"iPhone 11 64GB",title:"iPhone 11 64GB",linkText:"https://bireysel.turktelekom.com.tr/cihazlar/akilli-telefon/iphone-11-64gb",comment:"​​​​​​​​Ultra geniş açılı çift kamerasıyla iPhone 11 Türk Telekom’da!​​​​"},{href:"https://bireysel.turktelekom.com.tr/ev-telefonu",imgSrc:"https://www.turktelekom.com.tr/SiteAssets/images/arama-gorselleri/ev-telefonu.png",imgAlt:"Ev Telefonu",title:"Ev Telefonu",linkText:"https://bireysel.turktelekom.com.tr/ev-telefonu",comment:"​​​​​​​​Ev Telefonu​​​​"},],n=="telefon"||t=="telefon")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checktelefonInterval)}}function checksifredegistirme(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://onlineislemler.turktelekom.com.tr/",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Online İşlemler",title:"Online İşlemler",linkText:"https://onlineislemler.turktelekom.com.tr/",comment:"Online İşlemler"},],n=="sifredegistirme"||t=="sifredegistirme")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checksifredegistirmeInterval)}}function checkEngelsiz(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://www.turktelekom.com.tr/destek/engellilere-ozel-hizmetler",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Engellilere Özel Hizmetler",title:"Engellilere Özel Hizmetler",linkText:"https://www.turktelekom.com.tr/destek/engellilere-ozel-hizmetler",comment:"Engellilere Özel Hizmetler"},{href:"https://bireysel.turktelekom.com.tr/ozel-programlar/erisilebilir-yasam/erisilebilir-yasam-teklifleri/erisilebilir-yasam-evde-internet-kampanyalarinda-25-indirim",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Erişilebilir Yaşam Evde İnternet Kampanyalarında %25 İndirim!",title:"Erişilebilir Yaşam Evde İnternet Kampanyalarında %25 İndirim!",linkText:"https://bireysel.turktelekom.com.tr/ozel-programlar/erisilebilir-yasam/erisilebilir-yasam-teklifleri/erisilebilir-yasam-evde-internet-kampanyalarinda-25-indirim",comment:"Erişilebilir Yaşam Evde İnternet Kampanyalarında %25 İndirim!"},{href:"https://bireysel.turktelekom.com.tr/ozel-programlar/erisilebilir-yasam/erisilebilir-yasam-teklifleri/erisilebilir-yasam-faturali-mobil-tekliflerde-25-indirim",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Erişilebilir Yaşam Faturalı Mobil Tekliflerde %25 indirim!",title:"Erişilebilir Yaşam Faturalı Mobil Tekliflerde %25 indirim!",linkText:"https://bireysel.turktelekom.com.tr/ozel-programlar/erisilebilir-yasam/erisilebilir-yasam-teklifleri/erisilebilir-yasam-faturali-mobil-tekliflerde-25-indirim",comment:"Erişilebilir Yaşam Faturalı Mobil Tekliflerde %25 indirim!"},{href:"https://kurumsal.turktelekom.com.tr/dijital-donusum-uygulamalari/dijital-mesajlasma-ve-reklam/engelsiz-mesaj",imgSrc:"https://kurumsal.turktelekom.com.tr/tt-dijital-donusum-uygulamalari/PublishingImages/icons/engelsiz-mesaj.png",imgAlt:"Engelsiz Mesaj",title:"Engelsiz Mesaj",linkText:"https://kurumsal.turktelekom.com.tr/dijital-donusum-uygulamalari/dijital-mesajlasma-ve-reklam/engelsiz-mesaj",comment:"Engelsiz Mesaj"},{href:"https://bireysel.turktelekom.com.tr/dijital-servisler/erisilebilirlik-uygulamalari/engelliler-icin-ucretsiz-esim-uygulamasi",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Engelliler için ESİM Uygulaması",title:"Engelliler için ESİM Uygulaması",linkText:"https://bireysel.turktelekom.com.tr/dijital-servisler/erisilebilirlik-uygulamalari/engelliler-icin-ucretsiz-esim-uygulamasi",comment:"Engelliler için ESİM Uygulaması"},],n=="engelsizyasam"||t=="engelsizyasam")for(i=0;i<cardInfo.length;i++){let n=`
              <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
              <div class="image-block">
              <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
              <div class="text-block">
              <h4>${cardInfo[i].title}</h4>
              <p class="link">${cardInfo[i].linkText}</p>
              <p>${cardInfo[i].comment}</p>      
              </div>
              </a>
              `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkEngelsizInterval)}}function checkborcsorgulama(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/mobil",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Mobil Borç-Alacak Sorgulama",title:"Mobil Borç-Alacak Sorgulama",linkText:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/mobil",comment:"Mobil Borç-Alacak Sorgulama"},{href:" https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/internet",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"İnternet Borç-Alacak Sorgulama",title:"İnternet Borç-Alacak Sorgulama",linkText:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/internet",comment:"İnternet Borç-Alacak Sorgulama"},{href:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/telefon",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Telefon Borç-Alacak Sorgulama",title:"Telefon Borç-Alacak Sorgulama",linkText:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/telefon",comment:"Telefon Borç-Alacak Sorgulama"},{href:" https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/tv",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"TV Borç-Alacak Sorgulama",title:"TV Borç-Alacak Sorgulama",linkText:"https://onlineislemler.turktelekom.com.tr/borc-alacak-sorgulama/tv",comment:"TV Borç-Alacak Sorgulama"},],n=="borcsorgulama"||t=="borcsorgulama")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkborcsorgulamaInterval)}}function checkfaturaodeme(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://onlineislemler.turktelekom.com.tr/fatura-sorgulama-odeme/mobil",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Fatura Ödeme",title:"Fatura Ödeme",linkText:"https://onlineislemler.turktelekom.com.tr/fatura-sorgulama-odeme/mobil",comment:"Fatura Sorgulama ve Ödeme"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/faturali-hat-islemleri",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Faturalı Hat İşlemleri",title:"Faturalı Hat İşlemleri",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/faturali-hat-islemleri",comment:"Mobil"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet/fatura-islemleri",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Fatura İşlemleri",title:"Fatura İşlemleri",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet/fatura-islemleri",comment:"Evde İnternet"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/lira-yukleme-ve-faturasiz-hat-islemleri",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Lira Yükleme ve Faturasız Hat İşlemleri",title:"Lira Yükleme ve Faturasız Hat İşlemleri",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/lira-yukleme-ve-faturasiz-hat-islemleri",comment:"Lira Yükleme ve Faturasız Hat İşlemleri"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/mobil-odeme-noktasi",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Mobil Ödeme Noktası",title:"Mobil Ödeme Noktası",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-mobil/mobil-odeme-noktasi",comment:"Mobil Ödeme Noktası"},],n=="faturaodeme"||t=="faturaodeme")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkfaturaodemeInterval)}}function checknakilbasvuru(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet/internet-paket-bilgileri#tab115 ",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Nakil İşlemi",title:"Nakil İşlemi",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-evde-internet/internet-paket-bilgileri#tab115l",comment:"Evde İnternet"},{href:"https://www.turktelekom.com.tr/yardim/bireysel-ev-telefonu/musteri-hizmetleri#tab189",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Ev Telefonu Nakil Başvurusu",title:"Ev Telefonu Nakil Başvurusu",linkText:"https://www.turktelekom.com.tr/yardim/bireysel-ev-telefonu/musteri-hizmetleri#tab189",comment:"Ev Telefonu"},{href:"https://www.turktelekom.com.tr/yardim/kurumsal-telefon/genel",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Kurumsal Telefon Yardım",title:"Kurumsal Telefon Yardım",linkText:"https://www.turktelekom.com.tr/yardim/kurumsal-telefon/genel",comment:"Ödeme Noktaları"},],n=="nakilbasvuru"||t=="nakilbasvuru")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checknakilbasvuruInterval)}}function checkarizasorgulama(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://onlineislemler.turktelekom.com.tr/ariza-islemleri/internet",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Arıza İşlemleri",title:"İnternet Arıza İşlemleri",linkText:"https://onlineislemler.turktelekom.com.tr/ariza-islemleri/internet",comment:"Arıza İşlemleri"},{href:"https://www.turktelekom.com.tr/hakkimizda/planli-calisma-duyurulari",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Planlı Çalışma Duyuruları",title:"Planlı Çalışma Duyuruları",linkText:"https://www.turktelekom.com.tr/hakkimizda/planli-calisma-duyurulari",comment:"Planlı Çalışma Duyuruları"},{href:"https://onlineislemler.turktelekom.com.tr/ariza-islemleri/telefon",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Arıza İşlemleri",title:"Telefon Arıza İşlemleri",linkText:"https://onlineislemler.turktelekom.com.tr/ariza-islemleri/telefon",comment:"Arıza İşlemleri"},{href:"https://onlineislemler.turktelekom.com.tr/bize-ulasin/mobil",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Bize Ulaşın - Mobil",title:"Bize Ulaşın - Mobil",linkText:"https://onlineislemler.turktelekom.com.tr/bize-ulasin/mobil",comment:"Bize Ulaşın"},{href:"https://onlineislemler.turktelekom.com.tr/bize-ulasin/internet",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Bize Ulaşın - İnternet",title:"Bize Ulaşın - İnternet",linkText:"https://onlineislemler.turktelekom.com.tr/bize-ulasin/internet",comment:"Bize Ulaşın"},],n=="arizasorgulama"||t=="arizasorgulama")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkarizasorgulamaInterval)}}function checkinternetpaketleri(){var n,t;if(document.querySelector(".ms-srch-group  .ms-srch-group-content")){getParameterByName("k")!=null&&getParameterByName("k")!="0"&&(n=convertTurkishChars(getParameterByName("k")));getParameterByHash("k")!=null&&getParameterByHash("k")!="0"&&(t=convertTurkishChars(getParameterByHash("k")));const r=document.querySelector(".ms-srch-group  .ms-srch-group-content");if(cardInfo=[{href:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari",imgSrc:"https://bireysel.turktelekom.com.tr/tt-evde-internet/PublishingImages/evde-internet-hizli-filtre.png",imgAlt:"Yeni Müşteri Kampanyaları",title:"Evde İnternet",linkText:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari",comment:"Yeni Müşteri Kampanyaları"},{href:"https://bireysel.turktelekom.com.tr/mobil/mevcut-musteri-tarife-ve-paketleri/tum-faturasiz-paketler",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Faturasız Paketler",title:"Mobil",linkText:"https://bireysel.turktelekom.com.tr/mobil/mevcut-musteri-tarife-ve-paketleri/tum-faturasiz-paketler",comment:"Faturasız Paketler"},{href:"https://bireysel.turktelekom.com.tr/mobil/yeni-musteri-tarife-ve-paketleri/faturali-tarifeler",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Faturalı Tarifeler",title:"Mobil",linkText:"https://bireysel.turktelekom.com.tr/mobil/yeni-musteri-tarife-ve-paketleri/faturali-tarifeler",comment:"Faturalı Tarifeler"},{href:"https://bireysel.turktelekom.com.tr/mobil/yeni-musteri-tarife-ve-paketleri/faturali-tarifeler?GroupName=Evimde%20Mobil%20WiFi%20Tarifeleri",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Evimde Mobil WiFi Tarifeleri",title:"Evimde Mobil WiFi Tarifeleri",linkText:"https://bireysel.turktelekom.com.tr/mobil/yeni-musteri-tarife-ve-paketleri/faturali-tarifeler?GroupName=Evimde%20Mobil%20WiFi%20Tarifeleri",comment:"Evimde Mobil WiFi Tarifeleri"},{href:"https://bireysel.turktelekom.com.tr/mobil/yurt-disi/yurt-disinda-faturali-kullanim",imgSrc:"https://www.turktelekom.com.tr/PublishingImages/images/piktogram/mobil/yurt-disi.png",imgAlt:"Yurt Dışında Faturalı Kullanım",title:"Yurt Dışında Faturalı Kullanım",linkText:"https://bireysel.turktelekom.com.tr/mobil/yurt-disi/yurt-disinda-faturali-kullanim",comment:"Yurt Dışında Faturalı Kullanım"},{href:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari/yeni-magnet-limitsiz-tarifesi",imgSrc:"/SiteAssets/images/arama-gorselleri/jenerik.png",imgAlt:"Yeni Magnet Limitsiz Tarifesi",title:"Yeni Magnet Limitsiz Tarifesi",linkText:"https://bireysel.turktelekom.com.tr/evde-internet/yeni-musteri-kampanyalari/yeni-magnet-limitsiz-tarifesi",comment:"Evde İnternet"},],n=="internetpaketleri"||t=="internetpaketleri")for(i=0;i<cardInfo.length;i++){let n=`
                  <a id="fixed-result-1" name="Item" data-displaytemplate="WebPageItem" class="search-result-item" href="${cardInfo[i].href}">
                  <div class="image-block">
                  <img src="${cardInfo[i].imgSrc}" alt="${cardInfo[i].imgAlt}"></div>
                  <div class="text-block">
                  <h4>${cardInfo[i].title}</h4>
                  <p class="link">${cardInfo[i].linkText}</p>
                  <p>${cardInfo[i].comment}</p>      
                  </div>
                  </a>
                  `;r.insertAdjacentHTML("beforebegin",n)}clearInterval(checkinternetpaketleriInterval)}}checkAltyapi();const checkAltyapiInterval=setInterval(checkAltyapi,100);checktelefon();const checktelefonInterval=setInterval(checktelefon,100);checksifredegistirme();const checksifredegistirmeInterval=setInterval(checksifredegistirme,100);checkEngelsiz();const checkEngelsizInterval=setInterval(checkEngelsiz,100);checkborcsorgulama();const checkborcsorgulamaInterval=setInterval(checkborcsorgulama,100);checkfaturaodeme();const checkfaturaodemeInterval=setInterval(checkfaturaodeme,100);checknakilbasvuru();const checknakilbasvuruInterval=setInterval(checknakilbasvuru,100);checkarizasorgulama();const checkarizasorgulamaInterval=setInterval(checkarizasorgulama,100);checkinternetpaketleri();const checkinternetpaketleriInterval=setInterval(checkinternetpaketleri,100);
